version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis

  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  cart-service:
    build: ./cart-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - product-service
      - user-service
      - cart-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway

volumes:
  mongo-data: